
version: '3.9'

services:
  fitness-tracker:
    container_name: fitness-tracker
    build:
      context: .
      dockerfile: Dockerfile
    image: fitness-tracker:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./dev.db:/app/dev.db
    environment:
      - DATABASE_URL=file:./dev.db
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
